# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Chunky Poster"
license = "MIT"
licenselink = ""
description = ""
homepage = "https://gitlab.com/virtualcursor/chunky-poster"
tags = []
features = []
min_version = "0.41"

[author]
  name = "virtualcursor"
  homepage = "https://strict-panda.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
