baseURL = "https://gohugo.io/"
title = "Hugo Themes"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = "hugo-authors"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Hugo Authors"
  description = "Lorem ipsum dolor sit amet."
  homepageImage = "/images/homepage-image.jpg"

  [params.social]
    rss = true
    email = "example@example.com"
    facebook = "http://localhost:1313"
    twitter = "http://localhost:1313"
    linkedin = "http://localhost:1313"
    stack-overflow = "http://localhost:1313"
    instagram = "http://localhost:1313"
    github = "http://localhost:1313"
    weibo = "http://localhost:1313"
    medium = "http://localhost:1313"
    pinterest = "http://localhost:1313"
    reddit = "http://localhost:1313"
    gitlab = "http://localhost:1313"
    mastodon = "http://localhost:1313"
    keybase = "http://localhost:1313"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "http://localhost:1313"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

