baseURL = "https://gohugo.io/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
  [params.social]
    rss = true
    email = "example@example.com"
    facebook = "http://localhost:1313"
    twitter = "http://localhost:1313"
    linkedin = "http://localhost:1313"
    stack-overflow = "http://localhost:1313"
    instagram = "http://localhost:1313"
    github = "http://localhost:1313"
    weibo = "http://localhost:1313"
    medium = "http://localhost:1313"
    pinterest = "http://localhost:1313"
    reddit = "http://localhost:1313"
    gitlab = "http://localhost:1313"
    mastodon = "http://localhost:1313"
    keybase = "http://localhost:1313"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

